name: Node.js CI

on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test:cov
    - uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
